### ISSUE TITLE
Allow users to preview automated refactorings before they are applied

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#101]
As a user I want to be presented with each refactoring before they are applied to the source file.
The UI should allow the user to accept / reject each refactoring.

**Comment by JnRouvignac** [comment]
See also http://www.viva64.com/en/b/0309/#ID0E5QBI which brings an interesting solution to this problem:

> We take into account the message code, the text of the current code line as well as the previous and next ones. But we don't take into account the line number
> [...]
> when one of the lines (previous, current or next one) changes, the analyzer restores the warning since the message's context has been changed and we can treat the message as if it were output for new (modified) code.

**Comment by JnRouvignac** [comment]
Here is the solution found by Findbugs creator. Search for the article named "Tracking defect warnings across versions". I have not read it yet.

**Comment by JnRouvignac** [comment]
Another one from the article "The Google FindBugs Fixit":

> To provide a control for this study, we recently introduced new “noise bug detectors” into FindBugs that report issues based on non-defect information such as the md5 hash of the name and signature of a method containing a method call and the name and signature of the invoked method. [...] These are designed to depend on roughly the same amount of surrounding context as other detectors.

**Comment by JnRouvignac** [comment]
This is an important requirement for people uneasy with automated refactorings.
It helps them to build trust in the tool.
See the research paper _Use, Disuse, and Misuse of Automated Refactorings_.

**Comment by JnRouvignac** [comment]
Another way to present code changes inline in "From Quick Fixes to Slow Fixes: Reimagining Static Analysis Resolutions to Enable Design Space Exploration":

> Color Annotations. FIXBUGS is designed to support change comprehension after selecting a resolution. Specifically, FIXBUGS applies color annotations directly on the editor to denote the parts of code that have been added or changed. In addition, the gutter shows a green plus icon to indicate added code, and a pencil icon to indicate a section of changed code.

**Comment by Fabrice-TIERCELIN** [comment]
Done
