### ISSUE TITLE
Java AST Search

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#11]
Using the File Search for refactoring suffer from the limits of regular expressions It would be nice to have a Java AST Search that ignores whitespace, expressions, or group of statements.

For this we need to define a DSL to express expression types, or statements we want to ignore, etc.

Here are a few examples of possible syntax:
- `if (EXPR<boolean>) { STMT+ }` any boolean expression in the if condition will match, and one or more statements in the body of the loop will match.
- `if (EXPR) { STMT+ }` same, but no type specified for the expression (even though nothing else than boolean can exist here).
- `if (IDENT != null) { try { IDENT.close(); } catch (TYPE IDENT) { STMT* } }` this must reuse be the same identifier, how to convey it? The type of the identifier must be java.io.Closeable. How to convey it?
  *\* `if (IDENT1 != null) { try { IDENT1.close(); } catch (TYPE IDENT2) { STMT* } }`
  *\* `if (EXPR1<java.io.Closeable> != null) { try { EXPR1.close(); } catch (TYPE IDENT) { STMT* } }`to convey it?

Difficulties:
- See some of the difficulties pointed above
- How to reconcile regular expressions like operators (*, +) with Java language operators?
- It must be usable from a limited [TextField](http://en.wikipedia.org/wiki/Text_box)

See:
- AspectJ for specifying [pointcuts](http://www.eclipse.org/aspectj/doc/next/progguide/semantics-pointcuts.html)
- [Coccinelle](http://coccinelle.lip6.fr) for the specification of the [Semantic Patch Language]{http://coccinelle.lip6.fr/docs/index.html} with [SmPL examples](http://coccinellery.org)

**Comment by JnRouvignac** [comment]
Will this be needed when #111 is implemented?

**Comment by Fabrice-TIERCELIN** [comment]
We already use AST.

**Comment by JnRouvignac** [comment]
The idea was more to have something like structural search/replace in IntelliJ, but that was a wild dream anyway.
That would require a lot of effort.
