### ISSUE TITLE
ReduceVariableScope sample output currently appears not refactored?

### ISSUE THREAD

**Issue by twhitmorenz** [JnRouvignac/AutoRefactor#122]
Hi Jean-Noël,

I'm looking at your AutoRefactor plugin and very interested in the "reduce variable scopes" factoring -- but notice that the current samples don't appear to show it working.

I'm interested to try reducing variable scopes in an automatic way, as I have a large codebase suffering from this problem. Also interested by your latest work moving to a full CFG!

Regards,
Thomas Whitmore
Bravura Solutions

**Comment by JnRouvignac** [comment]
Hi Thomas,

The samples are ready, but this is not working yet. You can follow issue #7 to track progress (I have not started yet).
I first need to implement the CFG as described in issue #93 .
Thanks for expressing your interest.

I am closing this issue as a duplicate of #7.

**Comment by JnRouvignac** [comment]
Consider joining the discussion on gitter (see the badge on the first page)

**Comment by twhitmorenz** [comment]
Thanks Jean-Noël.
