### ISSUE TITLE
Collection.addAll() generates code that does not compile

### ISSUE THREAD

**Issue by gboismal** [JnRouvignac/AutoRefactor#123]
## Given
following code:
Where Type is a subclass of AbstractType
```java
Set<Type> anotherSet = ...
Set<AbstractType> mySet = new HashSet<>(); 
mySet.addAll(anotherSet);
```
# When

...automated refactorings are applied...
# Then
Generated code does not compile:
```java
Set<AbstractType> mySet = new HashSet<>(anotherSet); 
```

**Comment by JnRouvignac** [comment]
The end state is similar to #121. Maybe there is possible code reuse here.
