### ISSUE TITLE
Should not try to call .equals() on primitive

### ISSUE THREAD

**Issue by xpoinsard** [JnRouvignac/AutoRefactor#128]
The refactoring changed a condition from
```java
filter.equals(SegConstants.ROOT_ID)
```
to 
```java
SegConstants.ROOT_ID.equals(filter)
```
where `SegConstants.ROOT_ID` is a primitive constant.
This cause a compilation error.

**Comment by JnRouvignac** [comment]
Thanks for the bug report

**Comment by JnRouvignac** [comment]
Fixed! I'll try to do a build this week-end.
