### ISSUE TITLE
New refactoring - Replace old Vector / Hastable APIs with List-ArrayList / Map-HashMap

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#13]
# Replace Vector and Hastable only methods with List and Map methods

Here are the replacements to do for Vector:
- `Vector()`  => `ArrayList()`
- `Vector(Collection c)` => `ArrayList(Collection c)`
- `Vector(int initialCapacity)` => `ArrayList(int initialCapacity)`
- `Vector(int initialCapacity, int capacityIncrement)` => `ArrayList(int initialCapacity)`
- `Vector.addElement()` => `List.add()`
- `Vector.capacity()` => ?
- `Vector.elementAt()` => `List.get()`
- `Vector.elements()` => `List.iterator()` - somewhat equivalent
- `Vector.firstElement()` => `List.get(0)` -- Hmmm is it equivalent? Need to use if statement to ensure size?
- `Vector.indexOf(Object, int)` => ?
- `Vector.lastElement()` => `List.get(Vector.size())` -- Hmmm is it equivalent? Need to use if statement to ensure size?
- `Vector.lastIndexOf(Object, int)` => ?
- `Vector.copyInto()` => `List.toArray()`
- `Vector.insertElementAt()` => `List.add()`
- `Vector.removeAllElements()` => `List.removeAll()`
- `Vector.removeElement()` => `List.remove()`
- `Vector.removeElementAt()` => `List.remove()`
- `Vector.setElementAt()` => `List.set()`
- `Vector.setSize()` => `while (col.size() < X) { col.add(null)`;
- `Vector.trimToSize()` => `ArrayList.trimToSize()`
- other??

And for Hashtable:
- `Hashtable.elements()` => `Hashtable.entrySet().iterator()` - somewhat
- `Hashtable.keys()` => `Hashtable.keySet().iterator()` - somewhat
- `Hashtable.rehash()` => ?
# Replace Vector and Hastable by ArrayList and HashMap when the variable is local to a method

Issue #14 should cover this one.

**Comment by Fabrice-TIERCELIN** [comment]
Done.
