### ISSUE TITLE
Exception when code is not implemented  for comments

### ISSUE THREAD

**Issue by bubulemaster** [JnRouvignac/AutoRefactor#131]
Hi,

congratulation for work.

When I use your tool, an exception raise :

Exception when applying refactorings to file "xxxxxx.java": Code is not implemented  for comments situated after the target node for the Javadoc

I check file, but I don't understand what's happen.

Regards,

**Comment by JnRouvignac** [comment]
Hi,

You've found a bug! Thanks for reporting it.

Do you mind posting sample code showing the problem?
If not, could you obfuscate it and post it here?

**Comment by JnRouvignac** [comment]
Hello,

Did you make some progress on reproducing the issue with sample code that you can share?

**Comment by bubulemaster** [comment]
Hi,

sorry for delay :-(

I search what's happend, and I extract sample of code that produce error.

If I remove all private member (static and not), error is not produce.

Not working :
'''
/*
 * File Name:  gfhfghghfghf
 * @author:    cccccc
 * @version:   1.6.0
 * 
 * Licensed 
 * Copyright 
 */
package hjfg.dfgdfg.fd.gd.g.dfg.;

import java.awt.Font;
import java.util.StringTokenizer;
import java.util.Vector;

import hjfg.dfgdfg.fd.gd.g.dfg.*;
import hjfg.dfgdfg.fd.gd.g.dfg.Titi;


/**
 * <p>The Class Toto.</p>
 * 
 * <p>@author: sdfsdfs.</p>
 */
public class Toto
{
	static private final String NEW_LINE = "\n";
	private Tata[] rtextdArr;
	private Tata[] rlinedArr;
	private Tata[] rrectdArr;
	private TataTata[] rlogodArr;
	private Vector rtextdVec = new Vector();
	private Vector rlinedVec = new Vector();
	private Vector rrectdVec = new Vector();
	private Vector rlogodVec = new Vector();
	private char alignment = LeftAlign.VALUE;
	int backgroundNumber = 0;

	private final static double SCALE_X = 0.393;
	// private double SCALE_Y = 0.374;
	private final static double SCALE_Y = 0.330; // shorten scale to manage one

	// more line

	// private int talonWidth = 159;

	// private double SCALE_Y = 1;
	// private double SCALE_X = 1;
	// COLUMN_NO * 9.8, (ascii(LINE_NO) - 64) * 15.6, --to make a new line at
	// the bottom
	/**
	 * <pre>
	 * 
	 * </pre>
	 */
	public Background()
	{
	}

	/**
	 * Gets the int value.
	 *
	 * @param str the str
	 * @return the int value
	 */
	public static int getIntValue(String str)
	{
		int val = 0;
		try
		{
			if (str.trim().length() > 0)
			{
				val = Integer.parseInt(str.trim());
			}
		}
		catch (Exception e)
		{
			return 0;
		}
		return val;
	}

}
'''

working :
'''
/*
 * File Name:  gfhfghghfghf
 * @author:    cccccc
 * @version:   1.6.0
 * 
 * Licensed 
 * Copyright 
 */
package hjfg.dfgdfg.fd.gd.g.dfg.;

import java.awt.Font;
import java.util.StringTokenizer;
import java.util.Vector;

import hjfg.dfgdfg.fd.gd.g.dfg.*;
import hjfg.dfgdfg.fd.gd.g.dfg.Titi;


/**
 * <p>The Class Toto.</p>
 * 
 * <p>@author: sdfsdfs.</p>
 */
public class Toto
{
	/**
	 * <pre>
	 * 
	 * </pre>
	 */
	public Background()
	{
	}

	/**
	 * Gets the int value.
	 *
	 * @param str the str
	 * @return the int value
	 */
	public static int getIntValue(String str)
	{
		int val = 0;
		try
		{
			if (str.trim().length() > 0)
			{
				val = Integer.parseInt(str.trim());
			}
		}
		catch (Exception e)
		{
			return 0;
		}
		return val;
	}

}
'''

**Comment by JnRouvignac** [comment]
No worries. Many thanks for coming back with a code snippet.
I think the problem could be triggered by the commented out field.
I'll be sure only once I'll be able to run AutoRefactor on it.

**Comment by JnRouvignac** [comment]
Fixed.
Problem was due to `SCALE_Y` field having line comments both before, and after on the same line. The code to create a javadoc out of such two line comments was not implemented.
I pushed a new nightly if you want to test it.

Thanks again for reporting the issue!
