### ISSUE TITLE
Array refactoring does not respect operator before equal sign

### ISSUE THREAD

**Issue by p-** [JnRouvignac/AutoRefactor#134]
## Given
the following code:

    byte[] firstArray = {1,2,3,4};
    byte[] secondArray = {1,2,3,4};

    for (int i = 0; i < 4; i++) {
      firstArray[i] += secondArray[i];
    }

## When
applying automatic refactoring

### Actual
Code is wrongly refactored to:

    byte[] firstArray = {1,2,3,4};
    byte[] secondArray = {1,2,3,4};

    try {
      System.arraycopy(secondArray, 0, firstArray, 0, 4);
    } catch (IndexOutOfBoundsException e) {
      throw new ArrayIndexOutOfBoundsException(e.getMessage());
    }
  
The operator before the equal sign is not respected.

**Comment by JnRouvignac** [comment]
Hello,

Oh no I checked for an `Assignment`, but forgot to verify the operator is `=`!
Another JDT gotcha to look for!
Many thanks for reporting the problem!

**Comment by JnRouvignac** [comment]
Fixed and pushed a nightly.

**Comment by p-** [comment]
Tested the nightly. Works. Thanks!
