### ISSUE TITLE
Too much code is removed when refactoring specific one liners

### ISSUE THREAD

**Issue by p-** [JnRouvignac/AutoRefactor#135]
## Given
AutoRefactor	1.1.0.201506131411 (nightly)

the following code:

```java
    {
      try {
        assert true;
      } catch (Exception e) { }
    }
    
    public int getX() { return 5; }
```

## When
applying automatic refactoring

### Actual
Code is wrongly refactored to:

```java
    {
      try {
        assert true;
      } catch (Exception e) {
    }
    
    public int getX() {
```
  
Too much code is removed, resulting in compilation errors.

**Comment by JnRouvignac** [comment]
Hi,

Many thanks for this bug report. That's pretty ugly.
I don't expect to be able to work on it immediately.
I'll do my best to get a fix out quickly.

**Comment by JnRouvignac** [comment]
Finally I could find some time to fix this.
Weirdly enough, I could not reproduce the problem with `getX()`. Feel free to reopen this issue if I missed something.
I pushed a new nightly.

Thanks again for the clean report!

**Comment by p-** [comment]
Hi,
both samples work now correctly!

**Comment by JnRouvignac** [comment]
Great!
