### ISSUE TITLE
New refactoring - Simplify length checking

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#139]
## Given

The following condition:

``` java
boolean b1 = array.length <= 0;
boolean b2 = s.length() <= 0;
boolean b3 = col.size() <= 0;

boolean b4 = array.length < 0;
boolean b5 = s.length() < 0;
boolean b6 = col.size() < 0;
```
## When

... automatic refactorings are applied ...
## Then

code is refactored to:

``` java
boolean b1 = array.length == 0;
boolean b2 = s.length() == 0;
// or if java >= 1.6:
// boolean b2 = s.isEmpty();
boolean b3 = col.isEmpty();

boolean b4 = false;
boolean b5 = false;
boolean b6 = false;
```

**Comment by JanecekPetr** [comment]
boolean b2 = s.length() == 0;
    boolean b3 = col.size() == 0;

should actually be 

    boolean b2 = s.isEmpty();
    boolean b3 = col.isEmpty();

**Comment by JnRouvignac** [comment]
Good point.
I will update the issue to reflect this.

Note, there is already a refactoring that later converts `col.size() == 0` to `col.isEmpty()`. See #116.
But you're right, since we're at it, it is better to directly use the correct API.

Thinking out loud: Maybe can I iterate on the `ITypeBinding` and see there is a `isEmpty()` method and then use it instead of outputting `size() > 0` or `length() > 0`?

**Comment by cal101** [comment]
Please don't use duck type guessing here. Do this kind of refactoring only for known interfaces and classes.

**Comment by JnRouvignac** [comment]
You are right @cal101.
Better safe than sorry when it comes to refactoring.

**Comment by Fabrice-TIERCELIN** [comment]
Done
