### ISSUE TITLE
RemoveUnneededThisExpressionRefactoring: Simplification leads to compile error

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#160]
Don't simplify
```
x = this.<AClass>m();
```

to

```
x = <AClass>m();
```

**Comment by cal101** [comment]
Here a complete case testst against 9bd5df12abaa9fac6201ed3302a3b8ed00bdd731

```
 package de;
 
 import java.util.List;
 
 public class This {
      public List<Class> list(Class... clazzes) {
 	return null;
      }
      public List<Class> getAutoloadPackages() {
-        return this.<Class>list(This.class);
+        return <Class>list(This.class);
      }
 }

```

**Comment by cal101** [comment]
To be explicit: The bug is still present in most current version.

**Comment by JnRouvignac** [comment]
Eclipse complains:

> Unused type arguments for the non generic method list(Class...) of type This; it should not be parameterized with arguments <Class>

I did not know this was even possible!

**Comment by cal101** [comment]
Hey, you wanted to compete with javac ;-)

**Comment by JnRouvignac** [comment]
I did not want to compete with javac, but I am definitely learning a lot about Java's corner cases and the JLS thanks to this project!!

**Comment by cal101** [comment]
Me, too.
