### ISSUE TITLE
UseDiamondOperatorRefactoring: do not remove type parameter

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#163]
Do not remove second <Object> in

```java
final Set<Object> objects = new HashSet<Object>(getNodes().asSet());
```

If type parameter of argument of constructor is NOT <Object> and HashSet-type parameter is <Object> than better safe than sorry and leave it alone.

**Comment by JnRouvignac** [comment]
@cal101 Is it a duplicate of issue #121?
 If it is, then please close it.

**Comment by cal101** [comment]
Duplicate.
