### ISSUE TITLE
CollectionRefactoring: Not suitable for Stack

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#169]
This

```java
    final Stack<X> todo = new Stack<X>();
    todo.addAll(someList);
```

can't be converted to

```java
    final Stack<X> todo = new Stack<X>(someList);
```

because `java.util.Stack` does not have this constructor. (And so maybe others?)

**Comment by JnRouvignac** [comment]
Right `java.util.Stack` is a subclass of `java.util.Vector`.
I must do exact type checking (equals) rather than `instanceof`.

**Comment by JnRouvignac** [comment]
Actually no.
I remember checking all the Collection classes for the existence of a constructor with a Collection argument, but I apparently screwed up on that one.

Thanks for reporting this issue!
