### ISSUE TITLE
RemoveUnnecessaryLocalBeforeReturnRefactoring: parts missing

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#170]
Do not refactor

```java
Connection connection;
connection = ...
connection = (Connection) LogProxyFactory.createLogProxy(connection, Connection.class, log);
return connection;
```

to

```java
Connection connection;
connection = ...
return (Connection) ;
```

**Comment by JnRouvignac** [comment]
I cannot reproduce this issue.

**Comment by cal101** [comment]
OK, will provide complete example.

**Comment by cal101** [comment]
I could not locate the original case I had but I have:

```
    @Override
     public Throwable[] getExceptions() {
-        Throwable[] t = {};
         return t;
     }
 ```

**Comment by cal101** [comment]
The original case does still happen but the source code is difficult to reduce and it looks like a combination of refactorings causing it to happen. Let's stay with the easy Throwable case above and I open a new ticket if i have a complete test case.

**Comment by JnRouvignac** [comment]
@cal101 If you can reproduce the original case, then open a new bug.
