### ISSUE TITLE
RemoveUselessModifiersRefactoring: infinite loop

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#171]
An infinite loop has been detected for file XXX.java. A possible cause is that code is being incorrectly refactored one way then refactored back to what it was. Fix the code before pursuing. Possible culprit ASTVisitor classes are: org.autorefactor.refactoring.rules.RemoveUselessModifiersRefactoring

The code text is not changed between loops.

Is it because "Modifier" does not seem to implement equals() at least in Java 7?

**Comment by JnRouvignac** [comment]
Do you have such code? An annotated method and modifiers that are out of order and need to be reordered?

```java
    abstract static public class FixModifierOrderSampleClass implements Closeable {
        @Override
        synchronized public void close() {
        }
    }
```

(See https://github.com/JnRouvignac/AutoRefactor/blob/master/samples/src/test/java/org/autorefactor/refactoring/rules/samples_in/RemoveUselessModifiersSample.java)

**Comment by cal101** [comment]
Yes, because that reordering and removing of useless modifiers has not happened yet.

**Comment by cal101** [comment]
If you have a hint where to add some (probably temporary) debug to pin point the problem just tell.
