### ISSUE TITLE
Don't take an int for a character

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#172]
Because of

``` java
    @Test
    public void testChar() {
        char a = 'A';
        assertThat("it is: " + a)
                .isEqualTo("it is: A");
        assertThat("it is: " + (int)a)
                .isEqualTo("it is: 65");
    }
```

the following refactoring is wrong for c being a character (or a float or a double or a long(?)):

``` java
-    throw new InvalidIdException("invalid char in id: " + in + ", code: " + (int) c);
+    throw new InvalidIdException("invalid char in id: " + in + ", code: " + c);
```

**Comment by cal101** [comment]
Maybe the same issue:

StringBuilderRefactoring:

```
         public String toString() {
             StringBuffer buf = new StringBuffer(7);
-            buf.append(Integer.toString(c));
+            buf.append(c);
             for (int j = buf.length(); j < 3; j++) {
```

for c being a char.

**Comment by JnRouvignac** [comment]
Definitely the same kind of bug. I am thinking there are other variations of this issue:

```java
buf.append((int) c);
buf.append(Integer.toString(c));
String s = "" + (int) c;
String s = "" + Integer.toString(c);
```

I must be careful with all type conversions.

**Comment by JnRouvignac** [comment]
And I must check other types than `char` and `int` too.

**Comment by cal101** [comment]
Maybe some more micro refactoring helper methods that take care of not breaking compilage by checking for sematic changes because of overload or proper parentheses (string builder refactoring).
Abstracting the "uncompile" step.

**Comment by cal101** [comment]
2 sides of the coin:
1. The JDT structure is too concrete for abstract structural matching: too many details
2. It is also too concrete for replacement because you want  abstract structural changes instead

**Comment by Fabrice-TIERCELIN** [comment]
Fixed.
