### ISSUE TITLE
New refactoring - Replace qualified names by simple names

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#173]
## Given
The following code (with static imports):
```java
import static java.lang.Integer.*;
import java.lang.Integer;

// ...

    int i = Integer.valueOf("1");
```

## When
... automatic refactorings are applied ...

## Then
code is refactored to:
```java
    int i = valueOf("1");
```

# Subtleties
This same refactoring can be applied to methods/fields when static import exists.
Be extremely careful with static import ambiguities!

Also refactor qualified names (static imports or not, start imports or not) for fields/methods/types.
Also refactor use of static methods/fields/types in current class.

**Comment by cal101** [comment]
I think valueOf is one of the worsed examples to be used. 
Can be topped by using a static import for "of(...)".
Those methods get meaning only by its class name context so IMHO they should almost never be
statically imported.

IMHO a batter example is

```
   Arrays.asList(xxx) 
```

Be careful in case of 

```
    Arrays.<X>asList()
```

 that typically can't be converted even if my IDE sometimes does that which resuls in

```
   <X>asList()
```

**Comment by JnRouvignac** [comment]
I agree. I rushed writing this example and did not find a better example very quickly.
So we can exclude some overloaded method names like "valueOf", "of", ... After testing the rule on some real code bases, the list will very likely grow.

Thanks outlining for the pitfall of generic return types.
