### ISSUE TITLE
Unnecessary string builder refactoring?

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#192]
I think there is no need to replace

```
sb.append(STRING_LITERAL1 + STRING_LITERAL2)
```

with

```
sb.append(STRING_LITERAL1).append(STRING_LITERAL2)
```

because the compiler will concatenate them at compile time.

**Comment by Fabrice-TIERCELIN** [comment]
I have updated your issue by replacing _constant_ by _literal_. Is it?

**Comment by cal101** [comment]
+1

**Comment by Fabrice-TIERCELIN** [comment]
Why this a bug and not a feature?

**Comment by cal101** [comment]
Hmmm... 
I wanted to write unnecessary change and it is slightly slower and reduces the chance of the
append method to optimize memory and the code is longer.
On the other side you pay the price of an extra constant string in the original case.

If you dont't consider it a bug what is OK for me then don't call it a feature but instead close it.

If you have a general 




.
