### ISSUE TITLE
New refactoring - dead code: impossible instanceof

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#194]
Example:

``` java
String s = "";
if (s instanceof Integer) {
    // dead code
}
```

The same applies to uses of `Class.isAssignable()`

Basically anywhere that type conversion enters into play, such expressions can be replaced by `false`.

**Comment by strkkk** [comment]
instanceOf usage for incompatible types results in compile-time error - [JLS 15.20.2](https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.20.2), so the code in example will not compile anyway.

Looks like this check is more suitable for FindBugs or some other static analyzer.

**Comment by Fabrice-TIERCELIN** [comment]
Morever, it looks more like a mistake than simply a useless code. Removing this will make the mistake unnoticed. I agree, it should only be flagged and it should be manually fixed.

It's like removing this:
`myBigDecimal.add(BigDecimal.ONE);`

**Comment by Fabrice-TIERCELIN** [comment]
Bad idea, indeed. This code should be seen as wrong code. It is the scope of SpotBugs, not AutoRefactor. It would be harder to retrieve the problem if we touch to the problem.
