### ISSUE TITLE
Adding non Comparable objects to a sorted collection

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#195]
Adding a non `Comparable` to a `TreeSet` or to a `ConcurrentSkipListMap` will result in a class cast exception. Likewise for calling `Collections.sort(List)` on a `List` whose elements are not `Comparable` It would be nice to flag it.

However such functionality seems outside the scope of AutoRefactor.

**Comment by Fabrice-TIERCELIN** [comment]
Bad idea, indeed. This code should be seen as wrong code. It is the scope of SpotBugs, not AutoRefactor. I would say it's the scope of Java itself.
