### ISSUE TITLE
New refactoring - dead code: impossible checks

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#196]
Example:

``` java
byte b = Byte.MAX_VALUE;
if (b != Byte.MAX_VALUE + 1) {
    // dead code
}
```

Basically anywhere that type conversion enters into play, such expressions can be replaced by `false`.

**Comment by Fabrice-TIERCELIN** [comment]
Bad idea. This code should be seen as wrong code. It is the scope of SpotBugs, not AutoRefactor. It would be harder to retrieve the problem if we touch to the problem.
