### ISSUE TITLE
[patch] Replace unnecessary Boolean constant on boolean assignment

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [JnRouvignac/AutoRefactor#199]
Hi,

This is already done for declaration but not for assignment:
```
boolean isFound;
isFound = Boolean.TRUE;
```

...becomes:
```
boolean isFound;
isFound = true;
```

The patch with code and test is attached.
[BooleanAssignment.txt](https://github.com/JnRouvignac/AutoRefactor/files/384609/BooleanAssignment.txt)

**Comment by Fabrice-TIERCELIN** [comment]
[BooleanAssignment.txt](https://github.com/JnRouvignac/AutoRefactor/files/384619/BooleanAssignment.txt)

**Comment by JnRouvignac** [comment]
Thank you so much for your contribution!
I have committed the patch on your behalf, attributing authorship to you.

I made small changes:
- I renamed `visitAsssignment()` to `replaceBooleanObjectByPrimitive()` and added return statements where they were called.
- I added a null check which was missing from the code you modified

Thanks again!
