### ISSUE TITLE
[patch] Vertical scroll bar on the Choose refactorings... dialog

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [JnRouvignac/AutoRefactor#203]
Here is a patch that adds a vertical scroll bar on the refactoring list dialog.
![choose refactorings](https://cloud.githubusercontent.com/assets/20668759/17881756/332ef0c2-6908-11e6-86c7-5f953e325a49.png)
[Scrollbar.txt](https://github.com/JnRouvignac/AutoRefactor/files/431765/Scrollbar.txt)

**Comment by JnRouvignac** [comment]
Thanks for your patch!

I already have a scrollbar on my own machine which is running Linux Mint 17.3.
What OS are you using?

**Comment by Fabrice-TIERCELIN** [comment]
I have tested on Ubuntu 14, Ubuntu 16 and Windows 10. On all those OS, I haven't seen the bar. I have continued to analyze the issue. Actually, it's not the bar that is hidden, it's the table viewer that overflows. On this screenshot, you can note that we do not see the bottom border of the table viewer:
![windows_before](https://cloud.githubusercontent.com/assets/20668759/18102944/d9abbe70-6ef4-11e6-8d35-09ee817333ad.png)
That's the reason why there is no bar: the viewer is as higher as the table. I have changed a property to force the viewer to suit the size of the window:
![windows_after](https://cloud.githubusercontent.com/assets/20668759/18103201/e1a5bad0-6ef5-11e6-84ec-c431e7d8e6f6.png)
As you can see, I have also enlarged the filter text, to improve the feeling.

Here is the new patch:
[Scrollbar3.txt](https://github.com/JnRouvignac/AutoRefactor/files/445737/Scrollbar3.txt)

**Comment by JnRouvignac** [comment]
Thank you so much for fixing this issue I did not notice!
And thanks for the nice improvement on the text field.
