### ISSUE TITLE
[patch] JUnit refactoring

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [JnRouvignac/AutoRefactor#207]
Here is a (deprecated) patch for JUnit refactoring. It reuses the code for TestNG and applies it to JUnit. This first version does not deal with org.junit.Assert (only with junit.framework.Assert). Different improvements will be done later.

[JUnit.patch.txt](https://github.com/JnRouvignac/AutoRefactor/files/486631/JUnit.patch.txt)
To make the patch work, TestNGAssertRefactoring should be renamed AbstractUnitTestRefactoring. Or erase with the following (deprecated) files:
[AllRefactoringRules.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/486636/AllRefactoringRules.java.txt)
[AbstractUnitTestRefactoring.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/486634/AbstractUnitTestRefactoring.java.txt)
[TestNGAssertRefactoring.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/486639/TestNGAssertRefactoring.java.txt)
[JUnitAssertRefactoring.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/486638/JUnitAssertRefactoring.java.txt)
[JUnitAssertSample.java.in.txt](https://github.com/JnRouvignac/AutoRefactor/files/486637/JUnitAssertSample.java.in.txt)
[JUnitAssertSample.java.out.txt](https://github.com/JnRouvignac/AutoRefactor/files/486635/JUnitAssertSample.java.out.txt)

**Comment by JnRouvignac** [comment]
First of all, I can see this (JUnit <= 3 ?):

```java
    @Override
    protected String getUnitTestPackagePath() {
        return "junit.framework.";
    }
```

But it can also be (JUnit >= 4):

```java
    @Override
    protected String getUnitTestPackagePath() {
        return "org.junit.";
    }
```

So maybe both should be handled?

**Comment by Fabrice-TIERCELIN** [comment]
I have noticed it just before submitting the patch so I preferred to let it that way. Now it can be handled :)

**Comment by Fabrice-TIERCELIN** [comment]
Here is a new version that handles org.junit, merge codes and generalizes the expected detection:
[JUnit.patch.txt](https://github.com/JnRouvignac/AutoRefactor/files/510242/JUnit.patch.txt)
[AbstractUnitTestRefactoring.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/510238/AbstractUnitTestRefactoring.java.txt)
[AllRefactoringRules.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/510239/AllRefactoringRules.java.txt)
[JUnitAssertRefactoring.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/510241/JUnitAssertRefactoring.java.txt)
[JUnitAssertSample.java.in.txt](https://github.com/JnRouvignac/AutoRefactor/files/510240/JUnitAssertSample.java.in.txt)
[JUnitAssertSample.java.out.txt](https://github.com/JnRouvignac/AutoRefactor/files/510243/JUnitAssertSample.java.out.txt)
[TestNGAssertRefactoring.java.txt](https://github.com/JnRouvignac/AutoRefactor/files/510244/TestNGAssertRefactoring.java.txt)

**Comment by JnRouvignac** [comment]
Hi Fabrice,

I'd like to keep AutoRefactor commit history as linear as possible (I expect very few cases where we'd want to show branches). There are a few things we need to ensure before merging changes:
- No merge commits
- Rebase the changes before merging
- Squash meaningless commits

I am going to rework the history of master to make history linear again.

Thanks,
Jean-Noel

**Comment by Fabrice-TIERCELIN** [comment]
OK. I think I need more instructions for release branches and so on too.

**Comment by JnRouvignac** [comment]
Maybe a quick chat via gitter / hangout could help?
We just need to find a common time to chat :)

**Comment by JnRouvignac** [comment]
History is fixed now.
Sorry, this may cause some turbulence in your clone.
Please let me know if you have any trouble fixing it.
