### ISSUE TITLE
[patch] Missing code collection.add()

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [JnRouvignac/AutoRefactor#209]
When

``` Java
if (!col.contains(s)) {
    col.add(s);
}
```

Then

``` Java
if (col.add(s)) {
}
```

And then
(nothing)

The `CollectionRefactor` starts to refactor and the `CommonCodeInIfElseStatementRefactoring` considers the test as useless... but it is active. Here is a patch that fixes the issue like this:
When

``` Java
if (!col.contains(s)) {
    col.add(s);
}
```

Then

``` Java
col.add(s);
```

The patch also handles the case of `remove()`

[containsAsAStatement.patch.txt](https://github.com/JnRouvignac/AutoRefactor/files/518506/containsAsAStatement.patch.txt)

**Comment by JnRouvignac** [comment]
I believe this bug has been fixed in commit 8a3cd08 .
However your patch still adds the support for Set.remove().
