### ISSUE TITLE
New refactoring - Capitalize 'l' to upper case for long numbers

### ISSUE THREAD

**Issue by strkkk** [JnRouvignac/AutoRefactor#259]
## **Given**
`long value = 321l;`

## **When**
refactorings applied...

## **Then**
`long value = 321L;`

Reason is quite simple - lower case 'l' can be mixed with 1.
It is recommended to use upper case.

**Comment by Fabrice-TIERCELIN** [comment]
I agree with you. You should cite [this squid](https://sbforge.org/sonar/rules/show/squid:LowerCaseLongSuffixCheck).
