### ISSUE TITLE
Trying to hack: TypeBindingStub is missing methods

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#271]
Hi Autorefactor-Group!

I wanted to hack on autorefactor and think I followed the relevant steps of

https://github.com/JnRouvignac/AutoRefactor/wiki/Hacking-AutoRefactor

.

I downloaded eclipse oxygen (Eclipse IDE for Java EE Developers), installed the necessary plugin and maven stuff and then imported the maven project
from a clone of the git repository I created via "git clone" on my file system.

But I can't compile due to the following error:

The type TypeBindingStub must implement the inherited abstract method ITypeBinding.isIntersectionType()	

I suspect a version mismatch with eclipse plugin libraries but I don't understand where that should be selected.

Any help appreciated.

Cal

**Comment by Fabrice-TIERCELIN** [comment]
This method has been added since Neon. Either add a default implementation in your local code or use Eclipse Mars. We will decide later if we add it or not.

**Comment by cal101** [comment]
And I just wanted to add I have the same problem when using neon ;-)
Thanks for answering.
I you don't add the method please add a note to hacking page about the issue.
Since neon is mentioned on that page I didn't expect the code to be on mars level.

**Comment by Fabrice-TIERCELIN** [comment]
We have added the method to ensure compatibility with Neon and Oxygen.

**Comment by cal101** [comment]
If you don't expect problems from maven and eclipse using different library versions thats good enough for me.
