### ISSUE TITLE
CommonCodeInIfElseStatement - bug or need for marker and warning to dangerous refactorings in case of side effects?

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#272]
Thanks to @Fabrice-TIERCELIN I was able to get eclipse hacking environment up and running. 

I played around with refactorings and think some (sub) categorization or marking of refactorings may be useful if this is not considered a simple bug:

For example the refactoring:

    CommonCodeInIfElseStatement

does wrong refactorings in cases like

```
begin();
 if (needsBegin()) { 
  end(); 
 } else { 
  end(); 
}
```

This is bad code because of side effects but thats the target of auto refactor.

Moving the "end()" before the "if" will break the code.
So either the refactoring should be more conservative or the refactoring should be marked with some 
warning to check very carefully because of semantic changes.

Opinions?

**Comment by Fabrice-TIERCELIN** [comment]
Such a feature is planned but we don't know when.

**Comment by Fabrice-TIERCELIN** [comment]
Now, the statement order is kept
