### ISSUE TITLE
ArrayDequeRatherThanStackRefactoring - NPE

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#276]
Calls to local methods may have no expression and this leads to NPE

 at
org.autorefactor.refactoring.rules.AbstractClassSubstituteRefactoring.isObjectPassedInParameter(AbstractClassSubstituteRefactoring.java:347)

**Comment by Fabrice-TIERCELIN** [comment]
Already fixed.

**Comment by cal101** [comment]
Ack.
