### ISSUE TITLE
Eclipse Formatter config available?

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#284]
Moin!

AutoRefactor has very strict checkstyle rules and fixing them manually is wasteful.
Do you have an eclipse formatter configuration to format according to the AutoRector style?

Greetings,
   Cal

**Comment by Fabrice-TIERCELIN** [comment]
Here is my formatter:
[Formatter_for_AutoRefactor.xml.txt](https://github.com/JnRouvignac/AutoRefactor/files/1191623/Formatter_for_AutoRefactor.xml.txt)

**Comment by Fabrice-TIERCELIN** [comment]
I also configured this:
- Window -> Preferences -> Java -> Editor -> Save actions -> Perform the selected actions on save -> Additional actions -> Remove trailing white space on all lines
- Window -> Preferences -> General -> Editors -> Text Editors -> Show print margin -> Print margin column: 120

**Comment by cal101** [comment]
Perfect, thanks!
