### ISSUE TITLE
Autorefactor nightly is very old

### ISSUE THREAD

**Issue by gzsombor** [JnRouvignac/AutoRefactor#297]
I've noticed that neither the nightly builds http://autorefactor.org/nightly/ , nor the release builds are http://autorefactor.org/releases/ too new. Unfortunately the version on Marketplace is pretty old too: http://marketplace.eclipse.org/content/autorefactor

**Comment by JnRouvignac** [comment]
I have updated AutoRefactor nightly.
For the releases, I'll need to remember how to do a release. :)

**Comment by gzsombor** [comment]
And probably you should schedule the nightly build to run it _nightly_ :)

**Comment by JnRouvignac** [comment]
Aye, if only I did not have to push a button in the IDE. :)

**Comment by JnRouvignac** [comment]
Do you have suggestions @gzsombor ?

**Comment by gzsombor** [comment]
Could you use travis ?
It seems, they can build and deploy with custom scripts - https://docs.travis-ci.com/user/deployment/script/

**Comment by larsnaesbye** [comment]
Adding myself to the choir. A nightly that is even just a little younger than the current would be much appreciated :-)

**Comment by larsnaesbye** [comment]
@JnRouvignac , would it be possible to do one nightly release for now? This is because the current release and nightly don't work well with Java 9 projects :-)

**Comment by Fabrice-TIERCELIN** [comment]
The current development version is only supporting Java 5 to Java 8. Java 9 is not supported.

**Comment by Fabrice-TIERCELIN** [comment]
I don't have the access to release. However, this is what you can do:

1. Uninstall AutoRefactor
1. Kill Eclipse
1. Download [this file](https://github.com/JnRouvignac/AutoRefactor/files/2002254/org.autorefactor.plugin-1.2.0-SNAPSHOT.zip)
1. Unzip the two files in your `eclipse/dropin` folder
1. Launch Eclipse
1. Use a JDK 8 (too bad for the compilation errors)
1. Run AutoRefactor
1. Switch back to Java 9

This is the latest development version. Java 9 will be supported only when JDT Core 4.4.1 will be released.

**Comment by larsnaesbye** [comment]
That sounds like a fine plan :-) Thank you!

**Comment by Fabrice-TIERCELIN** [comment]
@larsnaesbye, 1.3.0 is out :) Don't forget to remove the two files in your `eclipse/dropin` folder.

**Comment by larsnaesbye** [comment]
Is it out? I can't find it...?

**Comment by Fabrice-TIERCELIN** [comment]
http://autorefactor.org/releases/

The official install location. It is explained [here](http://autorefactor.org).

**Comment by larsnaesbye** [comment]
I see 1.2.0 out here a few days ago, but not 1.3.0 as you mentioned....?

**Comment by Fabrice-TIERCELIN** [comment]
Oops!
