### ISSUE TITLE
(DD) RemoveFieldsDefaultValuesRefactoring - lambda removed

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#301]
```diff
 import java.util.Comparator;
 class t
 {
-Comparator<Foo>FOO_COMPARATOR=(o1,o2)->o1.getValue().toLowerCase()
-.compareTo(o2.getValue().toLowerCase());
+Comparator<Foo>FOO_COMPARATOR;
 class Foo
 {
 String getValue()
 {
 return null;
 }
 }
 }
```

**Comment by JnRouvignac** [comment]
AutoRefactor does not support Java 8 yet :(

**Comment by cal101** [comment]
Ok, I will stick with java 7.

**Comment by Fabrice-TIERCELIN** [comment]
I will disable this feature for Java 8 and close the bug. This way, you will still be able to refactor primitive types.

**Comment by cal101** [comment]
+1

**Comment by JnRouvignac** [comment]
Even though this code cannot know lambdas, I find it surprising it is removing them.
Maybe the code can be rewritten to avoid removing them?

**Comment by Fabrice-TIERCELIN** [comment]
JDT analyses the lambda expression as null literal (it does not leave a null pointer, it constructs a NullLiteral object) so there is no way to distinguish the two cases.
