### ISSUE TITLE
Lambdas refactorings

### ISSUE THREAD

**Issue by strkkk** [JnRouvignac/AutoRefactor#321]
1. Remove parenthesis for one argument without type declaration
1. Replace lambda with [method reference](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html) if possible
1. Remove return and brackets when there is one statement

# Given
The following code:
```
(someString) -> someString.trim().toLowerCase();
someString -> someString.toLowerCase();
someInt -> new ArrayList<>(someInt);
value -> SomeClass.staticMethod(value);
value -> someObject.method(value);
someString -> {return someString.trim().toUpperCase();};
```

# When
...automated refactorings are applied...

# Then
Code should be refactored to:
```
someString -> someString.trim().toLowerCase();
String::toLowerCase;
ArrayList::new;
SomeClass::staticMethod;
someObject::method;
someString -> someString.trim().toUpperCase();
```

**Comment by Fabrice-TIERCELIN** [comment]
This refactoring is very important because it would be the first Java 8 refactoring.
