### ISSUE TITLE
Add underscore separator for numbers

### ISSUE THREAD

**Issue by strkkk** [JnRouvignac/AutoRefactor#323]
Questionable, but can be useful to put _ in numbers to increase readability.
As an option, for different types of literals block size can be different (see below)
# Given
The following code:
```
int i = 1000000;
int hex = 0xdeadbeef;
int oct = 01234567;
int b = 0b1010101010101010101010101;
```

# When
...automated refactorings are applied...

# Then
Code should be refactored to:
```
// every 3 digits
int i = 1_000_000;
// every 4 digits
int hex = 0xdead_beef;
int oct = 0123_4567;
// every 8 digits
int b = 0b1_01010101_01010101_01010101;
```

**Comment by Fabrice-TIERCELIN** [comment]
Let's keep it in the backlog but I'm not sure it is a good idea.
