### ISSUE TITLE
Are qualified class references needed? (EnumSetRatherThanHashSetRefactoring)

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#336]
Hi!

I noticed that some refactorings like EnumSetRatherThanHashSetRefactoring but also others
change code to use qualified class references like

    `java.util.EnumSet.noneOf`

Is their some deeper reason for this?
Would you accept pull request so that the refactorings add those imports via JDT import rewrites?

Cal

**Comment by larsnaesbye** [comment]
Unless there is a namespace conflict with another class, then I’m up for it.

**Comment by cal101** [comment]
There is a refactoring that unqualifies names but that does too much IMO.
I think a separate refactoring that unqualifies class names with/without inner classes may be useful.
But I don't think it is a good idea to introduce more of these "if you execute A then execute B afterwords".
There are already too many of them.
IMO refactorings should produce a reasonable result with obvious cleanups done and not depending on other refactorings for this.

Some examples I consider "obvious":
- refactorings producing 
   `if (!!s.isEmpty())`
or   
`if ((s.isEmpty()))`

**Comment by Fabrice-TIERCELIN** [comment]
Indeed, this improvement is on my wishlist. The main reason it wasn't done was it was easier not to do this first. But don't be fooled, this improvement is not so easy. Each modified code should be modified inside a node flagged as DO_NOT_VISIT_SUBTREE. So we should flag the whole class. We have to check there is no name conflict. I think it should be done on the same refactoring to get this:
`new HashSet<>();` -> `new EnumSet<>();`
`new java.util.HashSet<>();` -> `new java.util.EnumSet<>();`

If it is done in a separate refactoring, we lose information.

**Comment by cal101** [comment]
I didn't tested it yet but using the reference returned by ImportRewrite should be enough.
Import is added if possible else qualified is returned.

https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2Frewrite%2FImportRewrite.html
