### ISSUE TITLE
RemoveOverridenAssignmentRefactoring - does not respect assignment with operator

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#340]
The `+=` assigment needs the initial value.

```
-            long l = 0;
+            long l;
             time0 = System.currentTimeMillis();
             l += colSup.getLong();
```

**Comment by strkkk** [comment]
This is valid for all operator tokens listed in [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.12)

> +=  -=  *=  /=  &=  |=  ^=  %=  <<=  >>=  >>>=

**Comment by Fabrice-TIERCELIN** [comment]
I make a cleaner code but I don't reproduce the bug. Can you provide a more complete case?

**Comment by cal101** [comment]
Here it comes. Fresh from the test case minifier.

```
class O
{
{
try
{
long l=0;
l+=1;
l=1;
}
catch(Exception e)
{
}
}
}
```

**Comment by Fabrice-TIERCELIN** [comment]
OK, I reproduce the bug. Thank you for all your bug reports! It's very useful :)

**Comment by cal101** [comment]
I have to thank JnRouvignac and you for your great work! Thank you very much!
I will continue with reports in "short style" assuming that most cases are easy to reproduce. Please do not hesitate to ask  for more complete examples when necessary.

**Comment by Fabrice-TIERCELIN** [comment]
Start with the easiest to report. We want as many reports as possible.

**Comment by cal101** [comment]
A few are on the way. 
The bulk was already reported some time ago and most of them were fixed.
