### ISSUE TITLE
JUnitAssertRefactoring - missing import

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#341]
I suspect that the refactoring assumes a wildcard support of `Assert.*`.

I have only a static import of ~~`import static org.junit.Assert.assertEquals;`~~
`import static org.junit.Assert.assertTrue;`
 and the following change does break the compile:

```
-                assertTrue(!img.getFilename().isEmpty());
+                assertFalse(img.getFilename().isEmpty());
```

**Comment by Fabrice-TIERCELIN** [comment]
How does it compile with only `import static org.junit.Assert.assertEquals;` and `assertTrue(!img.getFilename().isEmpty());`?

**Comment by cal101** [comment]
Ooops sorry, copy & paste error. The error is real but I copied the wrong static import.

**Comment by Fabrice-TIERCELIN** [comment]
# Given
The following code:
```Java
package org.autorefactor.refactoring.rules.samples_in;

import static org.junit.Assert.assertTrue;

public class JUnitAssertSample {
    public void shouldRefactorNegatedConditions(boolean b) {
        assertTrue(!b);
    }
}
```

# When
...automated JUnit refactoring is applied...

# Then
```Java
package org.autorefactor.refactoring.rules.samples_out;

import static org.junit.Assert.assertTrue;

public class JUnitAssertSample {
    public void shouldRefactorNegatedConditions(boolean b) {
        org.junit.Assert.assertFalse(b);
    }
}
```

Can you provide the whole code?

**Comment by cal101** [comment]
I make a test case.

**Comment by cal101** [comment]
This is a cool one ;-)

The Refactoring-Class-Instance is not stateless via AbstractUnitTestRefactoring
and if it is reused the refactorings of different compilation units will share state.
In this case the list of "static imports".
The chance of getting hit by this much bigger in my case when I applied it to 3000 classes
but I could reproduce the same problem  using 2 classes in the IDE.

A common place to collect state in visitors is the context so the visitors could be made stateless.
(Having a test that checks the visitors  would not harm ...)
Or you have to create more instances.

@Fabrice-TIERCELIN @JnRouvignac This is an architectural question.

**Comment by Fabrice-TIERCELIN** [comment]
This question is already answered. It should be done visiting the compilation unit. Here it was missing.
