### ISSUE TITLE
StringBuilderRefactoring swallows expression

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#348]
Do not steal my id:

```
                 DateFormatter formatter = new DateFormatter("yyyy");
                 Calendar cal = Calendar.getInstance();
                 cal.set(Calendar.YEAR, year);
-                return "actionstat-" + formatter.format(cal.getTime()) + (userid.isEmpty() ? "" : "-" + userid)
+                return "actionstat-" + formatter.format(cal.getTime()) + (userid.isEmpty() ? "" : "-")
                         + ".xml";
```

**Comment by Fabrice-TIERCELIN** [comment]
I don't reproduce. Can you provide a more complete case?

**Comment by cal101** [comment]
Sure. But has to wait until tomorrow.

**Comment by cal101** [comment]
Please try:
```
class l
{
final String userid="";
Object q()
{
return(userid.isEmpty()?"":"-"+userid)
;
}
}
```

**Comment by Fabrice-TIERCELIN** [comment]
I have run all the refactorings in it: I don't reproduce :(

**Comment by cal101** [comment]
Hmm, I ran with a slightly older version. Will try with most current version tomorrow. I am sorry for this.

**Comment by cal101** [comment]
I can't reproduce with current version. 
Since StringBuilderRefactoring got recent changes that may be a reason. 
I will take a detailed look at the results of StringBuilderRefactoring and will open a new case if needed.
Thanks for caring and please excuse me for wasting your time.
