### ISSUE TITLE
(RFE) StringBuilderRefactoring - questionable change

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#349]
I don't think the following change is an improvement:

```
-      newUrl.append("&" + URLParameter.SESSION_ID_PARAM + "=").append(newUsid);
+     newUrl.append("&").append(URLParameter.SESSION_ID_PARAM).append("=").append(newUsid);
```

The expression `"&" + URLParameter.SESSION_ID_PARAM + "="` is a compile time constant expression
because the inner term is a string literal constant. The compiler generates a single constant string for this. This allocates more space in the constant pool

The append variant is longer in code size, less readable IMO and does more work at runtime.

I suggest leaving those expressions alone and don't refactor them.

**Comment by Fabrice-TIERCELIN** [comment]
Confirmed by my decompiler

**Comment by cal101** [comment]
I commented on https://github.com/JnRouvignac/AutoRefactor/commit/2b4f26cdb4ce005f154f66f6ed59c4af2a1c0f23
did you get notifies for that?
