### ISSUE TITLE
Refactoring null checks

### ISSUE THREAD

**Issue by Naxos84** [JnRouvignac/AutoRefactor#362]
**I have the following code:**

```
if (myMember == null) {
  doSomething();
} else {
  doSomethingElse();
}
```

**This is refactored to:**

```
if (myMember != null) {
  doSomethingElse();
} else {
  doSomething();
}
```

For me it is way easier to understand of "==null" than of "!=null"

Though in the following case a refactoring would be useful.

```
if (myMember == null) {
  return;
} else {
  doSomethingElse();
}
```

should be refactored to:

```
if (myMember != null) {
  doSomethingElse();
}
```

Apparently I did not find anything to disable this refactoring cause I prefere checking "==null"

**Comment by Naxos84** [comment]
After cloning the repo and looking through the Code I found the rule that is responsible for that behaviour.
Namely: "WorkWithNullCheckedExpressionFirst".

Cause it is not starting with "null" I missed it.

issue can be closed I think.

**Comment by Fabrice-TIERCELIN** [comment]
OK, I close it.
