### ISSUE TITLE
Make content menu available even if projects are included which are not Java projects

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#387]
I wanted to run Autorefactor on my whole workspace. But as this workspace contains also non-Java projects the menu entry is not available.

Why not show it always and skip the non-Java projects during execution?

**Comment by Fabrice-TIERCELIN** [comment]
I think it's a good idea.

**Comment by vogella** [comment]
I think creates an issue, see below for error

To test, include a closed project into the selection.


![image](https://user-images.githubusercontent.com/139910/59592284-0a3f9280-90f0-11e9-96c4-8a75bd54ae2f.png)

**Comment by vogella** [comment]
Thanks, looks good.
