### ISSUE TITLE
Update to EPL 2.0

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#393]
Not sure what you licence policy is but I suggest to migrate to the EPL 2.0.

I did the same for the platform code base using some shells scripts but we recently fixed our copyright tooling, so this might also be used. Let me know if you consider this and if I can have a look if I can contribute this.

**Comment by Fabrice-TIERCELIN** [comment]
@JnRouvignac, what do you think about that?

**Comment by JnRouvignac** [comment]
I agree to license my AutoRefactor contributions to EPLv2.
Go for it.
