### ISSUE TITLE
Remove empty block does not remove all blocks

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#395]
Example:
````
@Test
	public void testZoomCommand() throws Exception {
		int times = 6;
		Assert.assertEquals(this.initialFontSize, text.getFont().getFontData()[0].getHeight());
	}
````

-> Block not removed

**Comment by Fabrice-TIERCELIN** [comment]
Witch block should be removed?

**Comment by cal101** [comment]
@vogella IMO this should be closed. A "block" is a syntactic unit present in the grammar typically
enclosed in '{' and '}.'
Indentation does not indicate blocks in java. This case is a case for the formatter.

**Comment by Fabrice-TIERCELIN** [comment]
@vogella, can you explain what this ticket means?

**Comment by vogella** [comment]
Sorry for not replying for a long time. I forgot what my use case was here. Sorry for the noise.
