### ISSUE TITLE
User cancel not respected

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#397]
I just ran a refactoring on a relatively build code base and pressed cancel on the job but the jobs were not cancelled.

Can you also support user cancellation?

**Comment by Fabrice-TIERCELIN** [comment]
I confirm it's very irritating >:)

**Comment by vogella** [comment]
Thanks you, very useful

Fabrice TIERCELIN <notifications@github.com> schrieb am Mo., 16. Sep. 2019,
04:57:
