### ISSUE TITLE
Update web-page with changes from "Use the same package as Eclipse"

### ISSUE THREAD

**Issue by jensli** [JnRouvignac/AutoRefactor#399]
The sample web-page does not work, because it has not been updated with the changes from this commit:

> Use the same package as Eclipse 
https://github.com/JnRouvignac/AutoRefactor/commit/2a6091b9ef3aa83415f8e4bf594c038ce99fbdf7

http://autorefactor.org/html/samples.html

**Comment by Fabrice-TIERCELIN** [comment]
Damn, you're right.
