### ISSUE TITLE
AllInOneMethodRatherThanLoopRefactoring is invalid for removeAll

### ISSUE THREAD

**Issue by jensli** [JnRouvignac/AutoRefactor#400]
The AllInOneMethodRatherThanLoopRefactoring makes an invalid transformation from a loop with `remove` to `removeAll`. The refactored code gives different results for lists with duplicates.

Example:

	var l1 = List.of("a");
	var l2 = List.of("a", "a");

	// Before applying the refactoring
	for (String s : l1) {
		l2.remove(s);
	}
	// l2 = [ "a" ]
	
	// After applying the refactoring
	l2.removeAll(l1);
	// l2 = []

This caused a bug in Eclipse:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549222
https://git.eclipse.org/r/#/c/144099/

**Comment by Fabrice-TIERCELIN** [comment]
I will think about it but I think the feature should be removed...

**Comment by jensli** [comment]
I *think* the refactoring is valid if the collection that is being removed from is a `Set`.

Thanks for a very nice tool!

**Comment by Fabrice-TIERCELIN** [comment]
I think so.

**Comment by jensli** [comment]
On a second though, the `remove` -> `removeAll` refactoring is not guaranteed to be valid even for `Set`s.

The reason is that sets might use definitions of equality that are different from `equals`. For example, `TreeSet` might use a `Comparator` to define equality. And since `removeAll` does not specify whether it uses equality that is defined on the receiver or the argument, switching from `remove` to `removeAll` might change the result.

For example, there is an issue with the implementation of `AbstractSet#removeAll` where the result depends on the relative sizes of the collections.
  
https://bugs.openjdk.java.net/browse/JDK-6394757

**Comment by Fabrice-TIERCELIN** [comment]
Actually, the entire rule is unsafe. The implementation of a collection can be rewritten so `add()`, `addAll()`, `remove()` and `removeAll()` can have any behavior.

This rule should be run with review.
