### ISSUE TITLE
Include Eclipse cleanups in the batch selection run

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#402]
I love the option to run AutoRefactor via multiple jobs on a larger code base. Could you also include the standard Eclipse cleanups into the possible selection of cleanups? This way I would also be easier to migrate more cleanups to Eclipse as we would not loose the ability to run the cleanups in parallel (standard Eclipse cleanup uses only one thread).

**Comment by Fabrice-TIERCELIN** [comment]
Above all, I think I need help :/ If I extrapolate, the migration of AutoRefactor into Eclipse will end in 6 years :(

**Comment by vogella** [comment]
I try to find some time in the next weeks, but cannot promise anything...

**Comment by cal101** [comment]
@Fabrice-TIERCELIN What is the most time consuming part migrating autorefactor refactorings into eclipse cleanups?

**Comment by vogella** [comment]
I think this is kind of fixed, as Autorefactoring is now part of the cleanup in Eclipse.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=558226 is still open to allow to allow to run the Eclipsei cleanups in batch similar to Autorefactoring as a Job. 

That would be awesome to have.

**Comment by cal101** [comment]
@vogella What about running refactorings as a command line job? (https://github.com/cal101/AutoRefactorCli) 
I revived my project last weekend and merged the autorefactor master  into it and it works with eclipse j2ee 2019-12 without any problems yet. (Not cleaned up or pushed yet)
Running cleanups this way was on my TODO list but I never got to it but got distracted by running
JDT refactorings this way.
Combining that with multi-thread support spounds interesting.

**Comment by vogella** [comment]
Would be definitely interesting to run the JDT cleanups via the command
line for me as autofactoring moves hopefully completely to JDT in the
future.

Maybe open a bug for that and contribute a Gerrit?

cal <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 13:35:
