### ISSUE TITLE
Use a single job only

### ISSUE THREAD

**Issue by Bananeweizen** [JnRouvignac/AutoRefactor#425]
The plugin produces quite some overhead by running multiple Eclipse jobs in parallel and updating their UI all the time. I've just profiled 20 seconds of SWT layouting operations in an overall 480 seconds of CPU time when running a single refactoring over a big workspace.
I would therefore like to refactor the code such that only a single job is executed and uses a worker pool internally, thereby distributing the load basically exactly the same way as before. Just the UI would change from many progress bars to a single one.
This change would also fix the wrong progress reporting (right now, the jobs all run from 0 to 100/number_of_cores percent only).
The partitioning job would probably not be needed anymore, since the worker pool should just grab work from a single queue instead of preparing N queues beforehand.

**Comment by Fabrice-TIERCELIN** [comment]
I think it's done, isn't it?
