### ISSUE TITLE
New refactoring - remove redundant throw declarations

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#43]
## Given

``` java
public void f() throws IOException, NullPointerException, Exception {
    ...
}
```
## When

triggering automatic refactoring
## Then

Code is rewritten to:

``` java
public void f() throws Exception {
    ...
}
```

Because Exception is a super type of IOException and NullPointerException.

**Comment by strkkk** [comment]
It is better to remove all unchecked exceptions from throws declaraction, they all redundant.
