### ISSUE TITLE
Vector to ArrayList refactoring does not remove import

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#436]
I just ran this refactoring on the eclipse.jdt.ui repo and JavaOutlinePage.java was refactored but the import was not removed.

**Comment by Fabrice-TIERCELIN** [comment]
Yes. I started to work on unused imports. I think the code works but I was not sure it was a good idea. Removing unused import is easy but only removing import that was used is harder. As Eclipse already offers to do this, I decided not to do this.

**Comment by vogella** [comment]
Ok, lots close this issue.

**Comment by cal101** [comment]
@vogella @Fabrice-TIERCELIN What about running the "remove unused imports cleanup" as automatic "post cleanup" after some autorefactor cleanups like this one? Rounds up this cleanup IMO.

**Comment by vogella** [comment]
This may result in unrelated changes, so I would leave that to the user.
