### ISSUE TITLE
Java 11 rules

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#438]
Hi Fabrice, which rules from autorefactor are in your opinion useful for code moving from Java 8 to Java 11? I will try to run them on the Eclipse platform code, as the 2020-09 release is allowed to use Java 11.

**Comment by Fabrice-TIERCELIN** [comment]
None. It handles Java up to Java 8. That's the reason "var cleanup" has been directly implemented into Eclipse.

**Comment by vogella** [comment]
:-)

This can be closed in this case
