### ISSUE TITLE
Quick assist - Convert string concatenations to StringBuilder appends

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#44]
As a developer I start writing a string concatenation until I figure out I need to convert it to StringBuilder appends.
## Given

``` java
String s = "foo" + "bar" + "baz";
```
## When

triggering the "convert to StringBuilder appends" quick fix
## Then

Code is rewritten to:

``` java
String s = new StringBuilder("foo").append("bar").apend("baz").toString;
```

Because Exception is a super type of IOException and NullPointerException.

**Comment by cal101** [comment]
@Fabrice-TIERCELIN IMHO this should be closed as "won't do". While the original is a single constant string the StringBuilder approach does work and needs more memory. Worse in all respects.

**Comment by Fabrice-TIERCELIN** [comment]
Yes.
