### ISSUE TITLE
JDT CleanUp StringBuilder - refactored code produces NPE

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#465]
Before:

```
String example = moduleName + "::" + toModelName(model) + ".new";
        if (!propertyExamples.isEmpty()) {
            example += "({" + StringUtils.join(propertyExamples, ", ") + "})";
        }			        }
        return example;
```

After:
```
       StringBuilder example = new StringBuilder(moduleName).append("::").append(toModelName(model)).append(".new");
        if (!propertyExamples.isEmpty()) {
            example.append("({").append(StringUtils.join(propertyExamples, ", ")).append("})");
        }
        return example.toString();
    }			
```

The new code is not null safe regarding 'moduleName'.

**Comment by cal101** [comment]
I think a simple solution can be using 
```
new StringBuilder("xxx").append(...
```
for initial values known to be non null (e.g. starting with strings and string constants)

and using 
```
new StringBuilder().append(moduleName)...
```
otherwise.

**Comment by Fabrice-TIERCELIN** [comment]
Yes, that's how I have fixed it in Eclipse:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=571570

**Comment by cal101** [comment]
Thanks for fixing and for the information!

**Comment by Fabrice-TIERCELIN** [comment]
Hi @cal101,

I see that you have `StringUtils.join(Collection<String>, String)`. If you are in Java 8+, you can replace its code by:
```java
String join(Collection<String> texts, String delimiter) {
  return String.join(delimiter, texts);
}
```

...and inline this.

**Comment by cal101** [comment]
Hi @Fabrice-TIERCELIN!

I forgot to thank you for the suggestion: Thank you!
Funnily enough I first learned about String.join only one week before your comment.
