### ISSUE TITLE
If rather than while and fall through causes compilation failure

### ISSUE THREAD

**Issue by nbauma109** [JnRouvignac/AutoRefactor#481]
There is a rule "if rather than while and falls through" that turns "while" into "if" but if there is a "continue" keyword inside the loop, it will result into a compilation failure if that "continue" keyword cannot be removed as part of the refactoring.

Here is a minimal reproducible example:

    while (Math.random()<0.5){
        if (Math.random()<0.4){
            continue;
        }
        break;
    }

It is refactored to:

    if (Math.random()<0.5 && Math.random()<0.4){
        continue;
    }

Which is wrong for the compiler

**Comment by nbauma109** [comment]
I also created a bug report at bugs.eclipse.org

**Comment by Fabrice-TIERCELIN** [comment]
Have you run the "if rather than while and falls through" rule alone?

**Comment by nbauma109** [comment]
With the rule alone, here is what I get:

if (Math.random()<0.5){
    if (Math.random()<0.4){
        continue;
    }
}

**Comment by Fabrice-TIERCELIN** [comment]
I fail to reproduce :( I have updated the [development version](https://github.com/JnRouvignac/AutoRefactor/wiki#The_development_version). Or you can test with the git source.

**Comment by nbauma109** [comment]
Ok I just tried with 1.3.0-SNAPSHOT and it's ok.

It was related to release 1.2.0.

**Comment by Fabrice-TIERCELIN** [comment]
OK, so I close the bug.
