### ISSUE TITLE
Refactoring results into an empty expression if()

### ISSUE THREAD

**Issue by nbauma109** [JnRouvignac/AutoRefactor#487]
I use version 1.3.0-SNAPSHOT.

I'm trying to refactor the following example

```
public class Snippet {
	public static void main(String[] args) {
		Object obj = new Object();
		String str = null;
		if (args.length == 2) {
			str = obj.toString();
		} else if (args.length == 1) {
			str = obj.toString();
		} else {
			System.out.println(str);
			return;
		}
	}
}
```

After refactoring, I obtained the following

```
public class Snippet {
	public static void main(String[] args) {
		Object obj = new Object();
		String str = null;
		if (() || (args.length == 1))
			if () {
			}
		else {
			System.out.println(str);
			return;
		}
		str = obj.toString();
	}
}
```

**Comment by cal101** [comment]
I am not directly involved in managing the AutoRefactor project but I am accompanying the project.
I couldn't reproduce with latest version.
What refactoring(s) did you apply?
Where do you got 1.3.0-SNAPSHOT from?
@Fabrice-TIERCELIN I suspect that updating the "official" builds is some of the project parts that are difficult to update. At least I got the expression.
But maybe it's easier to provide a more up-to-date build in a fork.
I can give that a try if there is any interest.

**Comment by nbauma109** [comment]
I built it myself on 14th may. It misses the 2 last commits. I can retest with a new build.

**Comment by nbauma109** [comment]
I've retried and still have the issue.

**Comment by cal101** [comment]
My setup is rather different and so it's far from representative.
I could not reproduce with your file but that may be because of this.

I was suprised that I got empty "if()" on another file with combination of:
RemoveEmptyIfCleanUp,ObsoleteMergeConditionalBlocksCleanUp,ObsoleteOutsideCodeRatherThanFallingThroughBlocksCleanUp

**Comment by Fabrice-TIERCELIN** [comment]
Hi @cal101 and @nbauma109,

Thank you for all your feedbacks. It's useful for AutoRefactor, Eclipse and any other migration destinations. I'm starting to migrate the rules in IntelliJ. For now, the first rule hasn't been merged yet but you can [add comment and reaction](https://github.com/JetBrains/intellij-community/pull/1550) to encourage them if you use this IDE.
