### ISSUE TITLE
Remove unnecessary casts can change the expected result

### ISSUE THREAD

**Issue by nbauma109** [JnRouvignac/AutoRefactor#489]
When I cast to a primitive like byte the results can change.
Consider this unit test:

```
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class ByteTest {
	@Test
	public void test() {
		int i = (byte) (-1 & 0xFF);
		assertEquals(-1, i);
	}
}
```

It is refactored to :

```
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class ByteTest {
	@Test
	public void test() {
		int i = (-1 & 0xFF);
		assertEquals(-1, i);
	}
}

```

Test result:

> java.lang.AssertionError: expected:<-1> but was:<255>

It it can help, Eclipse does not raise a warning and suggest a quick fix to remove cast.
Maybe it's possible to align this rule on Eclipse's original rule ?

**Comment by Fabrice-TIERCELIN** [comment]
If the feature of Eclipse works well, I won't fix it in AutoRefactor. Do I remove the rule?

**Comment by nbauma109** [comment]
Ok for me as eclipse can remove casts in bulk mode but ultimately it's your call.
