### ISSUE TITLE
A GitHub action to create pull request 

### ISSUE THREAD

**Issue by nbauma109** [JnRouvignac/AutoRefactor#495]
Does such a thing already exist or is in progress ?

1 pull request for 1 rule
On each pull request we'd have usual checks and status:
Compilation ok?
Unit tests ok?

I'd rather do changes before committing with source clean up and Sonarlint in eclipse but it can be tricky to check impact of each change.

**Comment by Fabrice-TIERCELIN** [comment]
The project is quite aborted. Sometimes we cherry-pick a cleanup to integrate it into an IDE. I'm rather contributing directly in IntelliJ:

https://github.com/JetBrains/intellij-community/pull/2202

**Comment by nbauma109** [comment]
Ok so the next question is, is there a command line interface for these ide refactorings ?
I found AutorefactorCli.

**Comment by Fabrice-TIERCELIN** [comment]
It's the only project I know as command line.
