### ISSUE TITLE
Bug - CommonCodeInIfElseStatementRefactoring should not remove side effects expressions

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#70]
## Given

``` java
if (file.mkdirs()) {
    i++;
} else {
    i++;
}
if (i++ == 0) {
    i++;
} else {
    i++;
}
```
## When

...applying automated refactorings...
## Then

code should be tranformed to:

``` java
file.mkdirs();
i++;
i++;
i++;
```
# Implementation

This could be done by maintaining a list of known methods with side effects. IT should be populated with methods from the JDKs and also be user-modifiable to allow supporting non JDK methods too.
This list will no doubt be useful for other refactorings too.

**Comment by Fabrice-TIERCELIN** [comment]
Handled
