### ISSUE TITLE
 Add a CFG (Control Flow Graph) builder based on Three Address Code

### ISSUE THREAD

**Issue by JnRouvignac** [JnRouvignac/AutoRefactor#93]
Being able to use a CFG allow to build new or safer refactorings.
It analyses better how and where variables are used, allowing to make more informed decisions. Moreover other analysis can be built on top of it.

See:
- http://en.wikipedia.org/wiki/Control_flow_graph
- http://en.wikipedia.org/wiki/Control_flow_analysis
- http://en.wikipedia.org/wiki/Data-flow_analysis
- http://en.wikipedia.org/wiki/Live_variable_analysis
- http://en.wikipedia.org/wiki/Reaching_definition

In #32, I realized the CFG needs to be built from an intermediate representation named a [Three Address Code](https://en.wikipedia.org/wiki/Three_address_code) (or TAC for short).
See an example [TAC model](https://crystalsaf.googlecode.com/svn-history/r342/trunk/CrystalPlugin/doc/edu/cmu/cs/crystal/tac/model/package-tree.html) for the Eclipse AST built for the [Crytal Eclipse plugin](https://code.google.com/p/crystalsaf/). I like the design of the three address code model with the variables.

&nbsp;

The CFG must be able to output DOT format for graph visualization.
Tools exist for interactive viewing (search for "interactive" or "view"): http://www.graphviz.org/content/resources

**Comment by JnRouvignac** [comment]
This page has got an interesting colour scheme for a CFG: http://www.semanticdesigns.com/Products/DMS/FlowAnalysis.html#ControlFlowAnalysis?Home=LifeAfterParsing

**Comment by JnRouvignac** [comment]
See also the CFG model of [CDT Codan](https://wiki.eclipse.org/CDT/designs/StaticAnalysis): [org.eclipse.cdt.codan.core.model.cfg](http://git.eclipse.org/c/cdt/org.eclipse.cdt.git/tree/codan/org.eclipse.cdt.codan.core/src/org/eclipse/cdt/codan/core/model/cfg)

**Comment by JnRouvignac** [comment]
See also OpenJDK's Graal project which features static analysis and [flow typing](https://en.wikipedia.org/wiki/Flow-sensitive_typing):
http://lafo.ssw.uni-linz.ac.at/papers/2015_CGO_Graal.pdf

In these slides see:
* slide 16: the colors used by IdealGraphVisualizer to represent control flow and data flow
* slide 72-73: interesting way to represent the flow typing for further perf analysis
* slide 74-75: sample code to build a flow typing graph

**Comment by nashid** [comment]
@JnRouvignac couple of questions:

(a) Why you mentioned we cant build CDF from an Eclipse JDT Parser. I have looked into https://github.com/JnRouvignac/AutoRefactor/issues/32 and it appears it was difficult to handle method invocations can throw exceptions. 

However, if we focus on intra-procedural analysis (method level) would that work?

(b) Are you still planning to add a CFG?

(c) Would be curious to know your high-level idea of how you are planning to incorporate Graal to build CFG?

**Comment by Fabrice-TIERCELIN** [comment]
@JnRouvignac has left the project and AutoRefactor will no longer be released. Any graph project is abandoned. AutoRefactor is only used to fuel Eclipse built-in cleanups.

**Comment by JnRouvignac** [comment]
Fabrice is right: I am no longer doing anything on this project unfortunately.
I have no spare time left to do anything here.
Apologies for the prolonged silence.

**Comment by Fabrice-TIERCELIN** [comment]
@JnRouvignac, as you're alive enough to tell us you are dead 😉 Can you please add write access to @cal101?

**Comment by JnRouvignac** [comment]
@cal101, you're invited!

**Comment by JnRouvignac** [comment]
Thanks @Fabrice-TIERCELIN  and @cal101 for making this project continue to live its life.
Well done to both of you! (and to others if there are any, sorry I did not follow closely)

**Comment by cal101** [comment]
Got it. Thanks.
 
@JnRouvignac I stumbled on your request for making the google refaster templates public. I retried. It's sad that nobody seems to care.

**Comment by JnRouvignac** [comment]
I think they do care, but simply don't have dedicated time. I have concluded that pure Google projects are flowing in the following direction almost exclusively: Google -> open source. The reverse is barely happening. I have made my peace with this now.

Of course there are pure community projects like kubernetes which do not suffer from this dynamic.

**Comment by JnRouvignac** [comment]
Closing since there won't be any CFG effort done.
